Repository GooseFX1/gfx-web-app, pull requests merged in 2022-06, with the labels that each got.

#339 Fix: Facebook Pixel App ID
  public/index.html
Labels: bug

#353 replace facebook profile with telegram
  src/api/NFTs/actions.ts
  src/context/nft_profile.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/PopupProfile.tsx
  src/types/nft_profile.d.ts
Labels: priority

#357 Collection Route Param - Get by Name
  src/context/nft_collections.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Home/Header.tsx
  src/pages/NFTs/Home/NFTImageCarouselItem.tsx
  src/pages/NFTs/Home/TabContent.tsx
  src/pages/NFTs/NFTs.tsx
  src/types/app_params.d.ts
Labels: enhancement

#364 Feature/farm v2
  src/constants.ts
  src/context/crypto.tsx
  src/context/price_feed_farm.tsx
  src/pages/Farm/Columns.tsx
  src/pages/Farm/ExpandedButtons.tsx
  src/pages/Farm/ExpandedDynamicContent.tsx
  src/pages/Farm/TableList.tsx
  src/web3/ssl.ts
Labels: enhancement

#365 General: Replaces Quicknode Devnet RPC
  src/context/settings.tsx
Labels: priority

#374 NFT Exchange: Fixed Price Default
  src/Router.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Home/OneOfOnesNFTs.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/Swap/Swap.tsx
  yarn.lock
Labels: enhancement

#378 General: Update Vulnerable Packages
  package.json
  src/types/fullpage.d.ts
Labels: bug
