Repository GooseFX1/gfx-web-app, pull requests merged in 2022-02, with the labels that each got.

#123 fix the bug on error upload by ignoring the error variable in the obj…
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/UploadCustom.tsx
Labels: bug

#129 NFT Market: Update data models
  src/api/NFTs/actions.ts
  src/context/nft_collections.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/Collection/LiveAuctionsTabContent.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/FooterCarousel.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTs.tsx
  src/types/nft_collections.d.ts
Labels: priority

#131 NFT Market: Resolves bug in file upload and preview
  src/pages/NFTs/Collectible/UploadCustom.tsx
Labels: bug

#132 Updates staging with PR #131
  src/pages/NFTs/Collectible/UploadCustom.tsx
Labels: bug

#139 NFT Market: Mint Single NFT Updates
  public/img/assets/nft-minting.svg
  public/img/assets/nft-preview.svg
  src/pages/NFTs/Collectible/AddAttribute.tsx
  src/pages/NFTs/Collectible/BottomButtonUpload.tsx
  src/pages/NFTs/Collectible/InfoInput.tsx
  src/pages/NFTs/Collectible/MintPaymentConfirmation.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/RoyaltiesStep.tsx
  src/pages/NFTs/Collectible/UpLoadNFT.tsx
  src/pages/NFTs/Collectible/UploadCustom.tsx
  src/pages/NFTs/Collectible/UploadProgress.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTFooter.tsx
Labels: bug, enhancement

#141 NFT Market: Homepage, Collections, and Single NFT UX Enhancements
  public/img/assets/avatar.svg
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/FooterCarousel.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTImageCarouselItem.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/PopupProfile.tsx
  src/types/nft_collections.d.ts
Labels: enhancement

#147 NFT Market: UI Enhanements
  public/img/assets/NFTs_icon.svg
  public/img/assets/crypto_icon copy.svg
  public/img/assets/crypto_icon.svg
  public/img/assets/home-slider-next.png
  public/img/assets/home-slider-next.svg
  public/img/assets/home-slider-prev.png
  public/img/assets/nft-preview-light.svg
  src/App.less
  src/Router.tsx
  src/context/index.ts
  src/context/nav_collapse.tsx
  src/layouts/App/App.tsx
  src/layouts/App/Header.tsx
  src/layouts/App/Tabs.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/AddAttribute.tsx
  src/pages/NFTs/Collectible/InfoInput.tsx
  src/pages/NFTs/Collectible/MintPaymentConfirmation.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/RoyaltiesStep.tsx
  src/pages/NFTs/Collectible/UpLoadNFT.tsx
  src/pages/NFTs/Collectible/UploadCustom.tsx
  src/pages/NFTs/Collectible/UploadProgress.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/CollectionCarousel.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTFooter.tsx
  src/pages/NFTs/NFTImageCarouselItem.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/Swap/Swap.tsx
  src/theme.tsx
Labels: enhancement

#146 Feature/nft details context
  public/img/assets/fixed-price-active.svg
  public/img/assets/fixed-price.svg
  public/img/assets/open-bid-active.svg
  public/img/assets/open-bid.svg
  src/context/nft_collections.tsx
  src/context/nft_details.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/LiveAuction.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collectible/mockData.js
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/CollectionCarousel.tsx
  src/pages/NFTs/Form/Donate.tsx
  src/pages/NFTs/GroupButton/GroupButton.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTTab.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Profile/Activity.tsx
  src/pages/NFTs/Profile/Card.styled.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/HeaderProfile.styled.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/NoContent.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/TabContent.styled.tsx
  src/pages/NFTs/SellCategory/SellCategory.tsx
  src/pages/NFTs/SellNFT/SellYourNFTView.tsx
  src/theme.tsx
  src/types/app_params.d.ts
  src/types/nft_collections.d.ts
  src/types/nft_details.d.ts
  src/types/nft_profile.d.ts
Labels: priority

#152 Updates with latest designs
  src/components/Categories.tsx
  src/layouts/App/Tabs.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/TradingHistoryTabContent.tsx
  src/pages/NFTs/NFTImageCarouselItem.tsx
  src/styles/utils.tsx
Labels: enhancement

#151 add likes and dislikes feature at cards and nft page
  src/api/NFTs/constants.ts
  src/context/nft_details.tsx
  src/context/nft_profile.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/Collection/LiveAuctionsTabContent.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/FixedPriceNFT/PurchaseModal.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/Profile/Card.styled.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/HeaderProfile.styled.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/unnamedUser.ts
  src/types/nft_details.d.ts
  src/types/nft_profile.d.ts
Labels: priority

#159 NFT Market: NFT Bid/Ask Logic
  package.json
  src/context/nft_details.tsx
  src/context/nft_profile.tsx
  src/layouts/App/Footer.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/actions.ts
  src/types/nft_details.d.ts
  src/web3/auction-house/AuctionHouseProgram.ts
  src/web3/auction-house/accounts/AuctionHouse.ts
  src/web3/auction-house/generated/accounts/AuctionHouse.ts
  src/web3/auction-house/generated/accounts/index.ts
  src/web3/auction-house/generated/errors/index.ts
  src/web3/auction-house/generated/instructions/buy.ts
  src/web3/auction-house/generated/instructions/cancel.ts
  src/web3/auction-house/generated/instructions/createAuctionHouse.ts
  src/web3/auction-house/generated/instructions/deposit.ts
  src/web3/auction-house/generated/instructions/executeSale.ts
  src/web3/auction-house/generated/instructions/index.ts
  src/web3/auction-house/generated/instructions/sell.ts
  src/web3/auction-house/generated/instructions/updateAuctionHouse.ts
  src/web3/auction-house/generated/instructions/withdraw.ts
  src/web3/auction-house/generated/instructions/withdrawFromFee.ts
  src/web3/auction-house/generated/instructions/withdrawFromTreasury.ts
  src/web3/auction-house/index.ts
  src/web3/ids.ts
  src/web3/index.ts
  src/web3/utils.ts
  yarn.lock
Labels: priority

#160 NFT Market: Execute Sale and Cancel AH Methods
  src/context/nft_details.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/actions.ts
Labels: priority

#165 NFT Market: Connection to Bid and Ask Endpoints
  src/api/NFTs/actions.ts
  src/components/TransactionFeedbackMsg.tsx
  src/components/index.ts
  src/context/nft_collections.tsx
  src/context/nft_details.tsx
  src/context/nft_profile.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/MintPaymentConfirmation.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/Collection/LiveAuctionsTabContent.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/CreateNFT/MyCreatedNFT.tsx
  src/pages/NFTs/FixedPriceNFT/FixedPriceNFT.tsx
  src/pages/NFTs/LiveAuctionNFT/LiveAuctionNFT.tsx
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTDetails/RemoveAskModalContent.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTDetails/TradingHistoryTabContent.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/Popup/PopupCustom.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/NFTs/actions.ts
  src/types/nft_collections.d.ts
  src/types/nft_details.d.ts
  src/types/nft_profile.d.ts
  src/web3/nfts/types.d.ts
  yarn.lock
Labels: priority

#176 NFT Market: Matched Bid Handler
  src/context/nft_profile.tsx
  src/layouts/App/Footer.tsx
  src/pages/Crypto/Crypto.tsx
  src/pages/Farm/Farm.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/Swap/Swap.tsx
  src/pages/Synths/Synths.tsx
  src/types/nft_profile.d.ts
Labels: priority
