Repository GooseFX1/gfx-web-app, pull requests merged in 2022-04, with the labels that each got.

#250 Farm: Updates StakedPlusEarned Value
  src/pages/Farm/TableList.tsx
  src/web3/stake.ts
Labels: bug

#254 Swap: Small Style Enhancement
  src/pages/Swap/SwapButton.tsx
  src/pages/Swap/shared.tsx
Labels: enhancement

#259 NFT Exchange: Fixes Remove Ask
  src/api/NFTs/actions.ts
  src/context/nft_details.tsx
  src/context/settings.tsx
  src/context/wallet.tsx
  src/pages/Farm/TableList.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/FooterCarousel.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/OpenBidNFT/MintModal.tsx
  src/pages/NFTs/Profile/Activity.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/TabContent.styled.tsx
  src/pages/NFTs/Profile/TableList.styled.tsx
  src/pages/NFTs/SellCategory/SellCategory.tsx
  src/pages/NFTs/actions.ts
  src/utils/notifications.tsx
  src/web3/stake.ts
Labels: bug, enhancement

#261 NFT Exchange: Update NFT Ask Price
  src/components/Modal.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/SellCategory/SellCategory.tsx
  src/styles/text.tsx
Labels: priority

#262 NFT Exchange: Fix Update Ask
  src/components/TransactionFeedbackMsg.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/utils/notifications.tsx
Labels: bug

#263 Feature/farm v2
  src/pages/Farm/ExpandedContent.tsx
  src/web3/stake.ts
Labels: enhancement

#265 NFT Exchange: Share Single NFT
  src/api/NFTs/actions.ts
  src/components/RewardDetails.tsx
  src/context/nft_profile.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Share.tsx
Labels: priority

#271 Feature/farm v2
  public/img/crypto/MSOL.svg
  src/constants.ts
  src/pages/Farm/ExpandedContent.tsx
  src/pages/Farm/FarmClickHandler.tsx
  src/pages/Farm/TableList.tsx
  src/theme.tsx
  src/utils/notifications.tsx
Labels: enhancement

#276 NFT Exchange: UI Enhancements
  public/img/assets/gfx_logo_gradient_dark.svg
  public/img/assets/gfx_logo_gradient_lite.svg
  public/img/assets/gfx_logo_white.webp
  public/img/assets/gfx_logo_white@2x.webp
  public/img/assets/gfx_logo_white@3x.webp
  src/constants.ts
  src/layouts/App/Footer.tsx
  src/layouts/App/Header.tsx
  src/pages/NFTs/NestQuestSingleListing.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
Labels: enhancement

#280 NFT Exchange: Beta Banner
  src/constants.ts
  src/pages/Farm/Farm.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/FooterCarousel.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTHeaderCarousel.tsx
  src/pages/NFTs/NestQuestSingleListing.tsx
  src/pages/NFTs/Profile/PopupProfile.styled.tsx
  src/pages/NFTs/Profile/PopupProfile.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/Swap/Swap.tsx
  src/types/nft_profile.d.ts
Labels: enhancement, priority

#282 NFT Exchange: Fix Bid Price Calc
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/SweepModal.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/utils/math.ts
Labels: bug, priority

#288 General: Adds Testing API Env
  src/api/index.ts
Labels: priority

#289 NFT Exchange: User Profile - Manage Escrow Button
  src/context/accounts.tsx
  src/pages/NFTs/Analytics/mockData.js
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collectible/data.js
  src/pages/NFTs/Collection/mockData.js
  src/pages/NFTs/CreateNFT/EditMyNFT.styled.tsx
  src/pages/NFTs/CreateNFT/EditMyNFT.tsx
  src/pages/NFTs/CreateNFT/MintItemView.tsx
  src/pages/NFTs/CreateNFT/MyCreatedNFT.tsx
  src/pages/NFTs/CreateNFT/MyNFT.styled.tsx
  src/pages/NFTs/CreateNFT/MyNFT.tsx
  src/pages/NFTs/CreateNFT/index.ts
  src/pages/NFTs/CreateNFT/mockData.js
  src/pages/NFTs/FixedPriceNFT/PurchaseModal.tsx
  src/pages/NFTs/FixedPriceNFT/mockData.js
  src/pages/NFTs/Header/index.ts
  src/pages/NFTs/Home/CollectionCarousel.tsx
  src/pages/NFTs/Home/FooterCarousel.tsx
  src/pages/NFTs/Home/Header.tsx
  src/pages/NFTs/Home/Loading.tsx
  src/pages/NFTs/Home/NFTFooter.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Home/NFTImageCarouselItem.tsx
  src/pages/NFTs/Home/Tab.tsx
  src/pages/NFTs/Home/TabContent.tsx
  src/pages/NFTs/Home/data.js
  src/pages/NFTs/Home/mockData.js
  src/pages/NFTs/NFTButton.tsx
  src/pages/NFTs/NFTDetails/BidModal.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTWrapper.tsx
  src/pages/NFTs/OpenBidNFT/MintModal.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/OpenBidNFT/index.ts
  src/pages/NFTs/PreviewPicture/PreviewPicture.tsx
  src/pages/NFTs/Profile/Card.styled.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/HeaderProfile.styled.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/mockData.js
  src/pages/NFTs/SellNFT/SellYourNFTView.tsx
  src/pages/NFTs/SellNFT/mockData.js
Labels: priority

#292 More UI update for the swap page
  public/img/assets/settings_dark_mode.svg
  public/img/assets/settings_lite_mode.svg
  public/img/assets/swap_switch.svg
  public/img/assets/swap_switch_dark_mode.svg
  public/img/assets/swap_switch_lite_mode.svg
  public/img/crypto/jup_dark.svg
  public/img/crypto/jup_lite.svg
  src/pages/NFTs/NestQuestSingleListing.tsx
  src/pages/Swap/Selector.tsx
  src/pages/Swap/Settings.tsx
  src/pages/Swap/Swap.tsx
  src/pages/Swap/SwapButton.tsx
  src/pages/Swap/SwapFrom.tsx
  src/pages/Swap/SwapTo.tsx
  src/theme.tsx
Labels: enhancement

#294 General: UI Enhancements
  public/img/assets/Refresh button.svg
  public/img/assets/no-nft-sweep-dark.svg
  public/img/assets/no-nft-sweep-lite.svg
  public/img/assets/plug-dark.svg
  public/img/assets/plug-lite.svg
  public/img/assets/plug2-dark.svg
  public/img/assets/plug2-lite.svg
  public/img/assets/refresh-icon.png
  public/img/assets/refresh_rate.svg
  src/context/price_feed.tsx
  src/pages/Farm/TableList.tsx
  src/pages/InvalidUrl.tsx
  src/pages/NFTs/Collectible/UpLoadNFT.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/Collection/SweepModal.tsx
  src/pages/Swap/Swap.tsx
  src/theme.tsx
Labels: enhancement
