Repository GooseFX1/gfx-web-app, pull requests merged in 2022-03, with the labels that each got.

#207 NFT Exchange: Homepage and Collection Enhancements
  src/components/RewardDetails.tsx
  src/layouts/App/Header.tsx
  src/layouts/App/Tabs.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/RoyaltiesStep.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/CollectionCarousel.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/Profile.tsx
Labels: bug, enhancement

#208 NFT Exchange: Mainnet Auction House
  src/Router.tsx
  src/components/RewardDetails.tsx
  src/layouts/App/Footer.tsx
  src/layouts/App/Tabs.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/actions.ts
  src/styles/constants.ts
  src/web3/auction-house/generated/instructions/buy.ts
  src/web3/auction-house/generated/instructions/cancel.ts
  src/web3/auction-house/generated/instructions/createAuctionHouse.ts
  src/web3/auction-house/generated/instructions/deposit.ts
  src/web3/auction-house/generated/instructions/executeSale.ts
  src/web3/auction-house/generated/instructions/updateAuctionHouse.ts
  src/web3/auction-house/generated/instructions/withdraw.ts
  src/web3/auction-house/generated/instructions/withdrawFromFee.ts
  src/web3/auction-house/generated/instructions/withdrawFromTreasury.ts
  src/web3/ids.ts
Labels: priority

#212 NFT Exchange: Fix bug in collections page reading yearly volume
  src/components/RewardDetails.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
Labels: bug

#213 Updates staging with bug fix in collections
  src/components/RewardDetails.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
Labels: bug

#215 General: Analytics Error
  public/img/assets/trade_icon.svg
  src/Router.tsx
  src/analytics.ts
  src/components/RewardDetails.tsx
  src/components/SelectRPC.tsx
  src/context/dark_mode.tsx
  src/layouts/App/Header.tsx
  src/layouts/App/Tabs.tsx
  src/layouts/App/WalletsModal.tsx
  src/pages/Crypto/Crypto.tsx
  src/pages/Farm/Farm.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/NFTFooter.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/Swap/Swap.tsx
  src/pages/Synths/Synths.tsx
Labels: bug

#218 NFT Exchange: Auto-create user ID on Wallet Connect
  src/context/nft_profile.tsx
  src/layouts/App/Header.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/Profile.tsx
Labels: priority

#221 NFT Exchange: Single NFT Data Fetching
  src/context/settings.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/CreateNFT/MintItemView.tsx
  src/pages/NFTs/CreateNFT/MyNFT.tsx
  src/pages/NFTs/FixedPriceNFT/FixedPriceNFT.tsx
  src/pages/NFTs/FixedPriceNFT/index.ts
  src/pages/NFTs/LiveAuctionNFT/BidModal.tsx
  src/pages/NFTs/LiveAuctionNFT/LiveAuctionNFT.tsx
  src/pages/NFTs/LiveAuctionNFT/index.ts
  src/pages/NFTs/LiveAuctionNFT/mockData.js
  src/pages/NFTs/NFTDetails/LeftSection.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTDetails/TradingHistoryTabContent.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/SellCategory/SellCategory.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/styles/text.tsx
  src/types/nft_details.d.ts
Labels: bug, priority

#223 NFT Exchange: Populate Home Page Banners
  public/img/assets/becoma-a-creator.png
  public/img/assets/nesetquest-egg.png
  public/img/assets/upcoming_features.webp
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/CollectionCarousel.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/NFTs/Slider/mockData.js
  src/theme.tsx
  src/types/theme.d.ts
Labels: priority

#228 NFT Exchange: Add Network to Bid/Ask Requests
  .gitignore
  .sample-env
  public/img/assets/NestQuest.png
  public/img/assets/nesetquest-egg.png
  public/img/assets/search.png
  public/img/assets/search.svg
  public/img/assets/search@2x.png
  public/img/assets/search@3x.png
  src/analytics.ts
  src/components/ArrowDropdown.tsx
  src/components/SearchBar.tsx
  src/components/SelectRPC.tsx
  src/context/crypto.tsx
  src/context/nft_details.tsx
  src/context/nft_profile.tsx
  src/context/orderbook.tsx
  src/context/price_feed.tsx
  src/layouts/App/GoFX.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NFTDetails/TradingHistoryTabContent.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/Synths/Synths.tsx
  src/theme.tsx
  src/types/theme.d.ts
Labels: priority

#227 Swap: Mainnet Swap - SOL to USDC
  src/constants.ts
  src/context/accounts.tsx
  src/context/settings.tsx
  src/context/swap.tsx
  src/context/token_registry.tsx
  src/web3/idl/swap2.json
  src/web3/ids.ts
  src/web3/swap2.ts
  src/web3/utils.ts
Labels: priority

#229 NFT Exchange: Discrepancy Bidding Small Amounts
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/OpenBidNFT/BidModal.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/pages/NFTs/actions.ts
Labels: bug

#232 NFT Exchange: User Profile - NFT Details
  src/api/NFTs/actions.ts
  src/context/nft_details.tsx
  src/pages/NFTs/Analytics/Tab.tsx
  src/pages/NFTs/Analytics/TabContent.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/NFTDetails/NFTDetails.tsx
  src/pages/NFTs/NFTTab.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/OpenBidNFT/OpenBidNFT.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/HeaderProfile.styled.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/TabContent.styled.tsx
Labels: priority

#234 Farm: Initial GOFX Staking
  src/App.tsx
  src/constants.ts
  src/layouts/App/Connect.tsx
  src/pages/Farm/Columns.tsx
  src/pages/Farm/ExpandedContent.tsx
  src/pages/Farm/Farm.tsx
  src/pages/Farm/FarmHeader.tsx
  src/pages/Farm/TableList.tsx
  src/pages/Farm/mockData.js
  src/web3/idl/stake.json
  src/web3/ids.ts
  src/web3/index.ts
  src/web3/stake.ts
Labels: priority

#244 updates staging with PR 243
  package.json
  src/constants.ts
  src/pages/Swap/SwapButton.tsx
  src/web3/layout.ts
  src/web3/swap2.ts
  src/web3/utils.ts
  ssl-wasm/gfx_ssl_wasm.d.ts
  ssl-wasm/gfx_ssl_wasm.js
  ssl-wasm/gfx_ssl_wasm_bg.js
  ssl-wasm/gfx_ssl_wasm_bg.wasm
  ssl-wasm/gfx_ssl_wasm_bg.wasm.d.ts
  ssl-wasm/package.json
  yarn.lock
Labels: priority

#245 Farm: Render Stake & Unstake Amounts
  src/pages/Farm/Columns.tsx
  src/pages/Farm/ExpandedContent.tsx
  src/pages/Farm/TableList.tsx
  src/web3/stake.ts
Labels: priority

#247 Farm: User Balance Fix
  src/constants.ts
  src/context/token_registry.tsx
  src/pages/Farm/ExpandedContent.tsx
  src/pages/Farm/TableList.tsx
Labels: bug
