Repository GooseFX1/gfx-web-app, pull requests merged in 2022-01, with the labels that each got.

#69 Fixes horizontal scroll bar in market selector
  src/App.less
  src/pages/Crypto/Order/CryptoSelector.tsx
  src/pages/Crypto/Order/Header.tsx
  src/pages/Crypto/OrderBook.tsx
Labels: bug, priority

#71 Fixes Crypto Trading Slider Recalculation
  src/pages/Crypto/Order/Total.tsx
  src/utils/misc.ts
Labels: bug

#73 fixes node version incompatibility with torus module
  .nvmrc
  package-lock.json
  yarn.lock
Labels: bug

#75 Initial API Client
  package.json
  src/api/NFTs/index.ts
  src/api/index.ts
  src/pages/NFTs/CollectionCarousel.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Home/mockData.js
  src/pages/NFTs/NFTImageCarouselItem.tsx
Labels: priority

#76 Creates Collections Context
  src/Router.tsx
  src/context/index.ts
  src/context/nft_collections.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/types/nft_collections.d.ts
Labels: priority

#82 NFT Market: Init User Context with API Integration
  public/img/assets/youtube.png
  src/api/NFTs/actions.ts
  src/api/NFTs/constants.ts
  src/api/NFTs/index.ts
  src/context/index.ts
  src/context/nft_collections.tsx
  src/context/nft_profile.tsx
  src/pages/NFTs/Collection/FixedPriceTabContent.tsx
  src/pages/NFTs/Collection/LiveAuctionsTabContent.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTAvatar.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Profile/HeaderProfile.tsx
  src/pages/NFTs/Profile/PopupCompleteProfile.tsx
  src/pages/NFTs/Profile/PopupProfile.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/TabContent.tsx
  src/pages/NFTs/Profile/TabProfile.tsx
  src/types/app_params.d.ts
  src/types/nft_profile.d.ts
Labels: priority

#84 Removes package-lock.json
  .gitignore
  package-lock.json
Labels: enhancement

#88 NFT Market: Profile Collect Content
  package.json
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/PopupProfile.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/TabContent.tsx
  src/types/nft_details.d.ts
  src/utils/borsh.ts
  src/utils/index.ts
  src/web3/index.ts
  src/web3/metaplex.ts
  src/web3/nfts/getParsedAccountByMint.ts
  src/web3/nfts/getParsedNftAccountsByOwner.ts
  src/web3/nfts/getParsedNftAccountsByUpdateAuthority.ts
  src/web3/nfts/index.ts
  src/web3/nfts/types.d.ts
  src/web3/nfts/utils.ts
  src/web3/utils.ts
  yarn.lock
Labels: priority

#91 NFT Market: User Activity
  src/context/nft_profile.tsx
  src/pages/NFTs/Profile/Activity.tsx
  src/pages/NFTs/Profile/ContentProfile.tsx
  src/pages/NFTs/Profile/Explore.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/pages/NFTs/Profile/NoContent.tsx
  src/pages/NFTs/Profile/Profile.tsx
  src/pages/NFTs/Profile/TabContent.tsx
  src/pages/NFTs/Profile/TabProfile.tsx
  src/types/nft_profile.d.ts
Labels: priority

#96 NFT Market: NFT Details from RPC Endpoint
  src/pages/NFTs/NFTDetails/AttributesTabContent.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/OpenBidNFT/mockData.js
  src/types/nft_details.d.ts
Labels: priority

#97 fix bug error in profile page
  src/pages/NFTs/Profile/Profile.tsx
Labels: bug

#102 add tooltip text farm page table headers
  src/components/Tooltip.tsx
  src/pages/Farm/Columns.tsx
Labels: enhancement

#109 NFT Market: Filters for Collections and Wallet Collectables
  src/components/SearchBar.tsx
  src/pages/NFTs/Collection/Collection.tsx
  src/pages/NFTs/Collection/CollectionHeader.tsx
  src/pages/NFTs/Collection/CollectionTabs.tsx
  src/pages/NFTs/Collection/OpenBidsTabContent.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
Labels: priority

#111 NFT Market: Mint Single NFT
  .env
  package.json
  src/context/nft_details.tsx
  src/layouts/App/DropDownButton.tsx
  src/pages/NFTs/Collectible/AddAttribute.tsx
  src/pages/NFTs/Collectible/BottomButtonUpload.tsx
  src/pages/NFTs/Collectible/InfoInput.tsx
  src/pages/NFTs/Collectible/LiveAuction.tsx
  src/pages/NFTs/Collectible/MintPaymentConfirmation.tsx
  src/pages/NFTs/Collectible/NewCollection.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/RoyaltiesStep.tsx
  src/pages/NFTs/Collectible/UpLoadNFT.tsx
  src/pages/NFTs/Collectible/UploadCustom.tsx
  src/pages/NFTs/Collectible/UploadProgress.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/types/app_params.d.ts
  src/types/nft_details.d.ts
  src/utils/borsh.ts
  src/utils/misc.ts
  src/web3/account.ts
  src/web3/ids.ts
  src/web3/index.ts
  src/web3/metaplex.ts
  src/web3/nfts/getParsedAccountByMint.ts
  src/web3/nfts/getParsedNftAccountsByOwner.ts
  src/web3/nfts/index.ts
  src/web3/nfts/metadata.ts
  src/web3/nfts/mintNFT.tsx
  src/web3/nfts/types.d.ts
  src/web3/nfts/utils.ts
  src/web3/programIds.ts
  src/web3/transactions.ts
  src/web3/utils.ts
  yarn.lock
Labels: priority

#115 NFT Market: Mint NFT Mainnet
  src/api/index.ts
  src/pages/NFTs/Collectible/LiveAuction.tsx
  src/pages/NFTs/Collectible/PreviewImage.tsx
  src/pages/NFTs/Collectible/UpLoadNFT.tsx
  src/pages/NFTs/Collectible/UploadProgress.tsx
  src/pages/NFTs/Collectible/index.tsx
  src/pages/NFTs/Header/Header.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Profile/Card.styled.tsx
  src/pages/NFTs/Profile/Card.tsx
  src/pages/NFTs/Profile/NFTDisplay.tsx
  src/web3/ids.ts
  src/web3/metaplex.ts
  src/web3/nfts/getParsedAccountByMint.ts
  src/web3/nfts/getParsedNftAccountsByOwner.ts
  src/web3/nfts/index.ts
  src/web3/nfts/metadata.ts
  src/web3/nfts/mintNFT.tsx
  src/web3/nfts/types.d.ts
Labels: enhancement
