Repository GooseFX1/gfx-web-app, pull requests merged in 2022-05, with the labels that each got.

#295 Swap: Implements Initial GFX SSL SDK
  package.json
  src/context/swap.tsx
  src/pages/Swap/Swap.tsx
  src/pages/Swap/SwapFrom.tsx
  src/theme.tsx
  src/web3/swap2.ts
  yarn.lock
Labels: priority

#308 NFT: Update to Custom Scroll
  src/App.less
  src/components/Modal.tsx
  src/context/nft_details.tsx
  src/context/settings.tsx
  src/index.css
  src/layouts/App/App.tsx
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Form/FormDoubleItem.tsx
  src/pages/NFTs/NFTDetails/RightSection.tsx
  src/pages/NFTs/NFTs.tsx
  src/pages/NFTs/Slider/NFTHomeSlider.tsx
  src/styles/text.tsx
  src/theme.tsx
Labels: bug, priority

#313 General: Geo Restriction
  src/Router.tsx
  src/context/settings.tsx
  src/pages/Restricted.tsx
  src/pages/Swap/Swap.tsx
  src/utils/index.ts
  src/utils/useBlacklisted.tsx
Labels: priority

#316 NFT Exchange: List Non-Curated NFTs
  src/api/NFTs/actions.ts
  src/api/NFTs/constants.ts
  src/api/index.ts
  src/components/MainButton.tsx
  src/index.css
  src/pages/NFTs/Collectible/SellNFT.tsx
  src/pages/NFTs/Collection/Card.tsx
  src/pages/NFTs/Home/FooterCarousel.tsx
  src/pages/NFTs/Home/Header.tsx
  src/pages/NFTs/Home/NFTHome.tsx
  src/pages/NFTs/Home/SingleItemListings.tsx
  src/pages/NFTs/NFTDetails/ImageShowcase.tsx
  src/pages/NFTs/NFTDetails/RemoveModalContent.tsx
  src/pages/NFTs/NFTDetails/RightSectionTabs.tsx
  src/pages/NFTs/NestQuestSingleListing.tsx
  src/types/nft_details.d.ts
Labels: priority

#317 Swap: Mobile Responsiveness
  package.json
  src/components/RewardsPopup.tsx
  src/layouts/App/App.tsx
  src/layouts/App/Connect.tsx
  src/layouts/App/Footer.tsx
  src/layouts/App/Header.tsx
  src/layouts/App/Tabs.tsx
  src/pages/Swap/Selector.tsx
  src/pages/Swap/Settings.tsx
  src/pages/Swap/Swap.tsx
  src/pages/Swap/SwapButton.tsx
  src/pages/Swap/SwapFrom.tsx
  src/pages/Swap/SwapTo.tsx
  src/pages/Swap/shared.tsx
  src/utils/misc.ts
  yarn.lock
Labels: priority

#323 NFT Exchange: Fix RangeError in 1of1 Mint
  src/pages/NFTs/Collectible/UploadCustom.tsx
  src/web3/nfts/mintNFT.tsx
  src/web3/transactions.ts
Labels: bug
